### ISSUE TITLE
Dynamic theme name seems to be having trouble loading the correct template, ActionView::MissingTemplate

### ISSUE THREAD

**Issue by starrychloe** [yoolk/themes_on_rails#7]
I'm getting these errors:

```
Started GET "/" for 127.0.0.1 at 2014-06-29 17:02:57 -0400
Processing by PostsController#index as HTML
Vanity: loading experiments from C:/Users/Chloe/workspace/Tyger/experiments
Vanity: loading metrics from C:/Users/Chloe/workspace/Tyger/experiments/metrics
*** {"session_id":"9541a5d2f4d6726039092b0ac22c3bae","_csrf_token":"RQB4Ji98sTvfETiZcW7caAYJYe0ytqUMC1QPO3f+2fo=","user_id":43,"theme":0}
*** loading theme bootstrap
Completed 500 Internal Server Error in 20ms

ActionView::MissingTemplate (Missing template layouts/ancap with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :jbuilder, :haml]}. Searched in:
  * "C:/Users/Chloe/workspace/Tyger/app/themes/bootstrap/views"
  * "C:/Users/Chloe/workspace/Tyger/app/views"
):
  app/controllers/posts_controller.rb:44:in `block (2 levels) in index'
  app/controllers/posts_controller.rb:43:in `index'
```

Notice it correctly selects theme bootstrap, but then tries to load a different template layout!

Here is my `#theme` selector in ApplicationController:

```
  theme lambda {|controller| 
    puts "*** #{controller.session.to_json}"
    name = ['bootstrap', 'ancap'][controller.session[:theme].to_i] 
    puts "*** loading theme #{name}"
    name
    }
```

Here is line 43 & 44 of `posts_controller` if you are curious:

```
respond_to do |format|
  format.html {render :index}
```

**Comment by DenisKhomusyak** [comment]
Every time I create a controller, I need to transfer files to a folder of the controller to the theme? No function built-in?
Example:
-
$ rails g themes_on_rails:generatelayouts SomeController
-
Just does'not exists in doc. about this.Thx.
